version: "3"
services:
    postgres:
        image: clkao/postgres-plv8
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        networks:
            - postgres

    #######################################################
    #  EventStoreDB
    #  https://developers.eventstore.com/clients/dotnet/5.0/#run-the-server
    # https://stackoverflow.com/questions/65272764/ports-are-not-available-listen-tcp-0-0-0-0-50070-bind-an-attempt-was-made-to
    # https://github.com/docker/for-win/issues/9272
    #######################################################
    eventstore.db:
        image: eventstore/eventstore:21.10.1-buster-slim
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        ports:
            - '1113:1113'
            - '2113:2113'

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    eventstore-volume-data:
